
version: '2'

services:

  orderer0:
    volumes:
      - ./data/orderer:/var/hyperledger/production

  #ca.org1:
  #  volumes:
  #    - ./data/ca:/var/hyperledger/production

  couchdb0:
    volumes:
      - ./data/couchdb0:/opt/couchdb/data

  couchdb1:
    volumes:
      - ./data/couchdb1:/opt/couchdb/data

  peer0.org1:
    volumes:
      - ./data/peer0:/var/hyperledger/production

  peer1.org1:
    volumes:
      - ./data/peer1:/var/hyperledger/production
