# https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/
# According to the docs, this requires `loadBalancer`, which does not work in minikube
---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: ingress
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: hostnames
#  namespace: hlf-service-network
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#spec:
#  backend:
#    serviceName: hostnames
#    servicePort: 80
---
# https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/provider/cloud-generic.yaml
#apiVersion: v1
#kind: Service
#metadata:
#  #namespace: ingress-nginx
#  name: ingress-nginx
#  namespace: kube-system
#  labels:
#    #app.kubernetes.io/name: ingress-nginx
#    #app.kubernetes.io/part-of: ingress-nginx
#    app.kubernetes.io/name: nginx-ingress-controller
#    app.kubernetes.io/part-of: kube-system
#spec:
#  externalTrafficPolicy: Local
#  type: LoadBalancer
#  selector:
#    #app.kubernetes.io/name: ingress-nginx
#    #app.kubernetes.io/part-of: ingress-nginx
#    app.kubernetes.io/name: nginx-ingress-controller
#    app.kubernetes.io/part-of: kube-system
#  ports:
#    - name: hostnames
#      port: 9000
#      targetPort: 9000
#      protocol: TCP
#    - name: ca-server
#      port: 7054
#      targetPort: 7054
#      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: kube-system
data:
# 53: "kube-system/kube-dns:53"         # used
# 80: "hlf-service-network/hostnames:80" # reserved
  5555: "kube-system/kube-dns:53"
  7777: "hlf-service-network/hostnames:80"
  7054: "hlf-service-network/ca-org1:7054"
  7050: "hlf-service-network/orderer0:7050"
  7051: "hlf-service-network/peer0-org1:7051"
# 7053: "hlf-service-network/peer0-org1:7053"
  8051: "hlf-service-network/peer1-org1:7051"
# 8053: "hlf-service-network/peer1-org1:7053"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: kube-system
data:
  5555: "kube-system/kube-dns:53"

# vim: sw=2:expandtab
