apiVersion: v1
kind: Service
metadata:
  labels:
    app: fabric-orderer
    org: {{ .Values.DomainName }}
    role: orderer
  name: orderer0
spec:
  ports:
  - port: 7050
    protocol: TCP
    name: orderer
  selector:
    app: fabric-orderer
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fabric-orderer
  name: orderer0-ops
spec:
  clusterIP: None
  ports:
  - port: 8443
    protocol: TCP
    name: operations
  selector:
    app: fabric-orderer
  type: ClusterIP
