apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fabric-orderer
    org: {{ .Values.DomainName }}
    role: orderer
  name: orderer0
spec:
  ports:
  - port: 7050
    protocol: TCP
    name: orderer
# - port: 8443
#   protocol: TCP
#   name: operations
  selector:
    app: fabric-orderer
  type: ClusterIP
status:
  loadBalancer: {}
