---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: hlf-service-network
  labels:
    app: busybox
    role: debug
spec:
  containers:
  - image: busybox
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: hlf-service-network
  labels:
    app: alpine
    role: debug
spec:
  containers:
  - image: alpine
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
