#!/bin/bash

if [ -z "$GOPATH" ]; then
    export GOPATH=${HOME}/go
fi

HSN_HOME=$(realpath $(dirname $0))/..

function read-env() {
    set -a
    source $HSN_HOME/.env
    set +a
}

function find-pod() {
    if [ -z "$1" -o -z "$2" ]; then
	echo "usage: findpod <retvar> <pod>"
	return
    fi
    local  __resultvar=$1
    local  ret=$(kubectl get pods -o=name | cut -f 2 -d / | grep $2 | head -1)
    eval $__resultvar="'$ret'"
}

function list-pods() {
    kubectl get pods -o=name | cut -f 2 -d /
}
