apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-peer{{ .Values.PeerNum }}-deployment
  labels:
    app: fabric-peer{{ .Values.PeerNum }}
    org: "{{ .Values.OrgName }}.{{ .Values.DomainName }}"
    role: peer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabric-peer{{ .Values.PeerNum }}
  template:
    metadata:
      labels:
        app: fabric-peer{{ .Values.PeerNum }}
        org: "{{ .Values.OrgName }}.{{ .Values.DomainName }}"
        role: peer
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9443'
    spec:
      volumes:
        - name: "peer{{ .Values.PeerNum }}-tls-secrets"
          secret:
            secretName: "peer{{ .Values.PeerNum }}-tls"
        - name: "peer{{ .Values.PeerNum }}-msp-volume"
          configMap:
            name: "peer{{ .Values.PeerNum }}-msp"
            items:
              - key: ca-cert.pem
                path: cacerts/ca-cert.pem
              - key: tlsca-cert.pem
                path: tlscacerts/tlsca-cert.pem
              - key: admin-cert.pem
                path: admincerts/admin-cert.pem
              - key: sign-cert.pem
                path: signcerts/sign-cert.pem
        - name: "peer{{ .Values.PeerNum }}-msp-keystore-secrets"
          secret:
            secretName: "peer{{ .Values.PeerNum }}-msp-keystore"
      hostname: "peer{{ .Values.PeerNum }}-{{ .Values.OrgName }}"
      #hostname: peer{{ .Values.PeerNum }}
      #subdomain: {{ .Values.OrgName }}
      containers:
        - name: peer{{ .Values.PeerNum }}-dind
          image: docker.io/docker:stable-dind
          ports:
            - containerPort: 2375
          securityContext:
            privileged: true
        - name: peer{{ .Values.PeerNum }}-container
          image: hyperledger/fabric-peer:{{ .Values.HLFTag }}
          command: ['peer', 'node', 'start']
          ports:
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 7053
            - containerPort: 9443
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9443
          volumeMounts:
            - name: peer{{ .Values.PeerNum }}-tls-secrets
              mountPath: /var/hyperledger/tls
            - name: peer{{ .Values.PeerNum }}-msp-volume
              mountPath: /var/hyperledger/msp
            - name: peer{{ .Values.PeerNum }}-msp-keystore-secrets
              mountPath: /var/hyperledger/msp/keystore
          env:
            # General
            - name: FABRIC_LOGGING_SPEC
              value: "DEBUG"
            - name: CORE_VM_ENDPOINT
              # value: "unix:///host/var/run/docker.sock" (talk to docker directly in vm)
              value: "http://localhost:2375" # Docker in docker is available here (dind)
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: "localhost:7052" # Chaincode will look for the peer here (dind)
            - name: CORE_VM_DOCKER_ATTACHSTDOUT
              value: "true"
            # State DB
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: "CouchDB"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: couchdb{{ .Values.PeerNum }}-creds
                  key: user
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb{{ .Values.PeerNum }}-creds
                  key: password
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              # In k8s, co-containers are on localhost
              #value: "couchdb{{ .Values.PeerNum }}.{{ .Values.OrgName }}.{{ .Values.DomainName }}:5984"
              value: "localhost:5984"
            # Peer config
            - name: CORE_PEER_PROFILE_ENABLED
              value: "true"
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "true"
            - name: CORE_PEER_NETWORKID
              value: "blockdaemon"
            - name: CORE_PEER_ID
              value: "peer{{ .Values.PeerNum }}.{{ .Values.OrgName }}.{{ .Values.DomainName }}"
            - name: CORE_PEER_ADDRESS
              value: "peer{{ .Values.PeerNum }}.{{ .Values.OrgName }}.{{ .Values.DomainName }}:7051"
            # Gossip
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "false"
            - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
              value: "true"
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: "peer{{ .Values.PeerNum }}.{{ .Values.OrgName }}.{{ .Values.DomainName }}:7051"
            # TLS and MSP
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_SERVERHOSTOVERRIDE
              value: "peer{{ .Values.PeerNum }}.{{ .Values.OrgName }}.{{ .Values.DomainName }}"
            - name: CORE_PEER_TLS_CERT_FILE
              value: "/var/hyperledger/tls/server.crt"
            - name: CORE_PEER_TLS_KEY_FILE
              value: "/var/hyperledger/tls/server.key"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: "/var/hyperledger/tls/ca.crt"
            - name: CORE_PEER_LOCALMSPID
              value: "{{ .Values.OrgName }}.{{ .Values.DomainName }}"
            - name: CORE_PEER_MSPCONFIGPATH
              value: "/var/hyperledger/msp"
            - name: CORE_OPERATIONS_LISTENADDRESS
              value: ":9443"
          # end peer-env.yaml for peer{{ .Values.PeerNum }}
          ###############################################
        # CouchDB for peer{{ .Values.PeerNum }}
        # couch{{ .Values.PeerNum }}-{{ .Values.OrgName }}.{{ .Values.DomainName }}
        - name: couch{{ .Values.PeerNum }}-container
          image: hyperledger/fabric-couchdb
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: couchdb{{ .Values.PeerNum }}-creds
                  key: user
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb{{ .Values.PeerNum }}-creds
                  key: password
          ports:
            - containerPort: 5984

