apiVersion: v1
kind: Service
metadata:
  labels:
    app: "fabric-peer{{ .Values.PeerNum }}"
    org: "{{ .Values.OrgName }}.{{ .Values.DomainName }}"
    role: peer0
  name: "peer{{ .Values.PeerNum}}-{{ .Values.OrgName }}"
spec:
  ports:
  - port: 7051
    protocol: TCP
    name: peer
  - port: 7053
    protocol: TCP
    name: gossip
# - port: 5984
#   protocol: TCP
#   name: couchdb
# - port: 9443
#   protocol: TCP
#   name: operations
  selector:
    app: "fabric-peer{{ .Values.PeerNum }}"
  type: ClusterIP
