          ###############################################
          # start peer-env.yaml for peer{{PEER}}
          env:
            # General
            - name: CORE_LOGGING_LEVEL
              value: "DEBUG"
            - name: CORE_VM_ENDPOINT
              value: "http://localhost:2375" # Docker in docker is available here
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: "localhost:7052" # Chaincode will look for the peer here
            - name: CORE_VM_DOCKER_ATTACHSTDOUT
              value: "true"
            # State DB
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: "CouchDB"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: couchdb{{PEER}}-creds
                  key: user
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb{{PEER}}-creds
                  key: password
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              # In k8s, co-containers are on localhost
              #value: "couchdb0.{{env.SUBDOMAIN1}}.{{env.DOMAIN}}:5984"
              value: "localhost:5984"
            # Peer config
            - name: CORE_PEER_PROFILE_ENABLED
              value: "true"
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "true"
            - name: CORE_PEER_NETWORKID
              value: "{{env.NETWORKID}}"
            - name: CORE_PEER_ID
              value: "peer{{PEER}}.{{env.SUBDOMAIN1}}.{{env.DOMAIN}}"
            - name: CORE_PEER_ADDRESS
              value: "peer{{PEER}}.{{env.SUBDOMAIN1}}.{{env.DOMAIN}}:7051"
            # Gossip
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "false"
            - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
              value: "true"
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: "peer{{PEER}}.{{env.SUBDOMAIN1}}.{{env.DOMAIN}}:7051"
            # TLS and MSP
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_SERVERHOSTOVERRIDE
              value: "peer{{PEER}}.{{env.SUBDOMAIN1}}.{{env.DOMAIN}}"
            - name: CORE_PEER_TLS_CERT_FILE
              value: "/var/hyperledger/tls/server.crt"
            - name: CORE_PEER_TLS_KEY_FILE
              value: "/var/hyperledger/tls/server.key"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: "/var/hyperledger/tls/ca.crt"
            - name: CORE_PEER_LOCALMSPID
              value: "{{env.SUBDOMAIN1}}.{{env.DOMAIN}}"
            - name: CORE_PEER_MSPCONFIGPATH
              value: "/var/hyperledger/msp"
          # end peer-env.yaml for peer{{PEER}}
          ###############################################
{# DO NOT REMOVE, we need it to prevent line concat in the % include also
 # vim: sw=2:expandtab:
 #}
