#!/bin/bash

set -e

tempfile="$(mktemp -q -t "$(basename "$0").XXXXXX" 2>/dev/null || mktemp -q)"
trap "{ rm -f ${tempfile}; }" EXIT

chmod og-rw ${tempfile}
echo "Generating new CA user/password"
CAUSER=$(openssl rand -base64 32 | tr -cd '[:alpha:]')
CAPASS=$(openssl rand -base64 32 | tr -cd '[:alpha:]')

echo CAUSER=\"${CAUSER}\" >> ${tempfile}
echo CAPASS=\"${CAPASS}\" >> ${tempfile}

for peer in 0 1; do
    echo "Generating new couchdb user/password for peer${peer}"
    cduser="CDUSER${peer}"
    cdpass="CDPASS${peer}"
    export ${cduser}=$(openssl rand -base64 32 | tr -cd '[:alpha:]')
    export ${cdpass}=$(openssl rand -base64 32 | tr -cd '[:alpha:]')
    echo ${cduser}=\"${!cduser}\" >> ${tempfile}
    echo ${cdpass}=\"${!cdpass}\" >> ${tempfile}
done
mv -f ${tempfile} .secrets
